<a href="https://colab.research.google.com/github/singhanand453/server.py/blob/master/anand.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#print("123")
import pandas as pd 
dict={"country":["india","usa","england","russia","canada"],
      "capital":["new delhi","wh dc","london","mosco","otawa"],
      "population":[1.3,0.45,0.30,0.52,0.39]}

x=pd.DataFrame(dict)
x.index=["IND","USA","US","RUSS","CA"]

print(x)

      country    capital  population
IND     india  new delhi        1.30
USA       usa      wh dc        0.45
US    england     london        0.30
RUSS   russia      mosco        0.52
CA     canada      otawa        0.39


In [0]:
import numpy as np
import numpy.matlib
x=np.matlib.zeros((3,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [0]:
import numpy as np
import numpy.matlib
print(np.matlib.zeros((2,2)))


[[0. 0.]
 [0. 0.]]


In [0]:
import numpy as np
import numpy.matlib
x=np.matlib.eye(n=3,M=3,k=0)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
import numpy as np
import numpy.matlib
x=np.matlib.identity(5,dtype=complex)
print(x)


[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]]


In [0]:
import numpy as np
x=np.random.randint(0,100,(5,5))
print(x)

[[15 82 66 83  4]
 [20 89 57 48 40]
 [37 25  0 62 84]
 [ 8 92 32 31 19]
 [85 24 82 92  6]]
